// Generated by CoffeeScript 1.9.1
(function() {
  "use strict";
  var LITERALS, Speed, TYPES, Types, _, breakIfEqual, createForce, extend, instanceOf, testValues, typeOf;

  instanceOf = function(type, value) {
    return value instanceof type;
  };

  typeOf = function(value, type) {
    if (type == null) {
      type = 'object';
    }
    return typeof value === type;
  };

  LITERALS = {
    'Boolean': false,
    'String': '',
    'Object': {},
    'Array': [],
    'Function': function() {},
    'Number': (function() {
      var number;
      number = new Number;
      number["void"] = true;
      return number;
    })()
  };

  TYPES = {
    'Undefined': function(value) {
      return value === void 0;
    },
    'Null': function(value) {
      return value === null;
    },
    'Function': function(value) {
      return typeOf(value, 'function');
    },
    'Boolean': function(value) {
      return typeOf(value, 'boolean');
    },
    'String': function(value) {
      return typeOf(value, 'string');
    },
    'Array': function(value) {
      return typeOf(value) && instanceOf(Array, value);
    },
    'RegExp': function(value) {
      return typeOf(value) && instanceOf(RegExp, value);
    },
    'Date': function(value) {
      return typeOf(value) && instanceOf(Date, value);
    },
    'Number': function(value) {
      return typeOf(value, 'number') && (value === value) || (typeOf(value) && instanceOf(Number, value));
    },
    'Object': function(value) {
      return typeOf(value) && (value !== null) && !instanceOf(Boolean, value) && !instanceOf(Number, value) && !instanceOf(Array, value) && !instanceOf(RegExp, value) && !instanceOf(Date, value);
    },
    'NaN': function(value) {
      return typeOf(value, 'number') && (value !== value);
    },
    'Defined': function(value) {
      return value !== void 0;
    }
  };

  TYPES.StringOrNumber = function(value) {
    return TYPES.String(value) || TYPES.Number(value);
  };

  Types = _ = {
    parseIntBase: 10
  };

  createForce = function(type) {
    var convertType;
    convertType = function(value) {
      switch (type) {
        case 'Number':
          if ((_.isNumber(value = parseInt(value, _.parseIntBase))) && !value["void"]) {
            return value;
          }
          break;
        case 'String':
          if (_.isStringOrNumber(value)) {
            return value + '';
          }
          break;
        default:
          if (Types['is' + type](value)) {
            return value;
          }
      }
    };
    return function(value, replacement) {
      if ((value != null) && void 0 !== (value = convertType(value))) {
        return value;
      }
      if ((replacement != null) && void 0 !== (replacement = convertType(replacement))) {
        return replacement;
      }
      return LITERALS[type];
    };
  };

  testValues = function(predicate, breakState, values) {
    var i, len, value;
    if (values == null) {
      values = [];
    }
    if (values.length < 1) {
      return predicate === TYPES.Undefined;
    }
    for (i = 0, len = values.length; i < len; i++) {
      value = values[i];
      if (predicate(value) === breakState) {
        return breakState;
      }
    }
    return !breakState;
  };

  breakIfEqual = true;

  (function() {
    var name, predicate, results;
    results = [];
    for (name in TYPES) {
      predicate = TYPES[name];
      results.push((function(name, predicate) {
        Types['is' + name] = predicate;
        Types['not' + name] = function(value) {
          return !predicate(value);
        };
        Types['has' + name] = function() {
          return testValues(predicate, breakIfEqual, arguments);
        };
        Types['all' + name] = function() {
          return testValues(predicate, !breakIfEqual, arguments);
        };
        if (name in LITERALS) {
          return Types['force' + name] = createForce(name);
        }
      })(name, predicate));
    }
    return results;
  })();

  extend = function(target, source, append) {
    var key, value;
    if (target == null) {
      target = {};
    }
    for (key in source) {
      value = source[key];
      if (_.isObject(value)) {
        extend(target[key], value, append);
      } else {

      }
      if (!(append && target.hasOwnProperty(key))) {
        target[key] = value;
      }
    }
    return target;
  };

  _.append = function(target, source) {
    return extend(_.forceObject(target), _.forceObject(source), true);
  };

  Speed = (function() {
    var align, format, resolveNameFunc, tooMany, warmup;

    format = function(nr, interval, char) {
      var formatted, i, index, length, pos, ref;
      if (interval == null) {
        interval = 3;
      }
      if (char == null) {
        char = '.';
      }
      if ('' === (nr = _.forceString(nr))) {
        return '';
      }
      length = nr.length - 1;
      formatted = nr[length--];
      if (length < 0) {
        return formatted;
      }
      pos = interval;
      for (index = i = ref = length; ref <= 0 ? i <= 0 : i >= 0; index = ref <= 0 ? ++i : --i) {
        if ((--pos % interval) === 0) {
          formatted = char + formatted;
          pos = interval;
        }
        formatted = nr[index] + formatted;
      }
      return formatted;
    };

    align = function(string, length) {
      var aligned, i, n, ref;
      if (length == null) {
        length = 20;
      }
      length -= string.length;
      aligned = '';
      if (length > 0) {
        for (n = i = 1, ref = length; 1 <= ref ? i <= ref : i >= ref; n = 1 <= ref ? ++i : --i) {
          aligned += ' ';
        }
      }
      if (align.right) {
        return aligned + string;
      }
      return string + aligned;
    };

    align.right = true;

    tooMany = function(calls) {
      if (calls > Speed.maxCalls) {
        console.log('You are trying to run more than ' + format(Speed.maxCalls) + ' calls, increase Speed.maxCalls if you really want this.');
        console.log('Aborting..');
        return true;
      }
    };

    warmup = function() {
      var i, n, ref, results;
      results = [];
      for (n = i = 1, ref = Speed.warmupCycles; 1 <= ref ? i <= ref : i >= ref; n = 1 <= ref ? ++i : --i) {
        results.push(n = n);
      }
      return results;
    };

    resolveNameFunc = function(ctx, name, func) {
      if (_.isFunction(name)) {
        func = name;
        name = 'anonymus-' + ++ctx.anonymusCount;
      }
      return [name, func];
    };

    Speed.Types = Types;

    Speed.details = false;

    Speed.rounds = 1;

    Speed.calls = 1;

    Speed.maxCalls = 100000000;

    Speed.warmupCycles = 1000000;

    Speed.run = function(callback, calls, rounds, details, name) {
      var average, count, end, i, kickOff, ref, round, start, totalElapsed;
      if (name == null) {
        name = 'anonymus';
      }
      if (!(callback = _.forceFunction(callback, null))) {
        return console.log(name);
      }
      rounds = _.forceNumber(rounds, Speed.rounds);
      calls = _.forceNumber(calls, Speed.calls);
      details = _.forceBoolean(details, Speed.details);
      if (tooMany(rounds * calls)) {
        return;
      }
      console.log('*speed.js* -> "' + name + '", ' + format(rounds) + ' rounds ' + format(calls) + ' calls');
      warmup();
      kickOff = Date.now();
      for (round = i = 1, ref = rounds; 1 <= ref ? i <= ref : i >= ref; round = 1 <= ref ? ++i : --i) {
        count = 0;
        start = Date.now();
        while (count++ < calls) {
          callback();
        }
        end = Date.now();
        if (details) {
          console.log('round: ' + round + ': ' + align((end - start) + ' ms', 9));
        }
      }
      totalElapsed = Date.now() - kickOff;
      average = format(~~(totalElapsed / rounds));
      totalElapsed = format(totalElapsed);
      console.log('average time for ' + align(format(calls) + ' calls : ') + align(average + ' ms', 9));
      console.log('total time for   ' + align(format(calls * rounds) + ' calls : ') + align(totalElapsed + ' ms', 9));
      return console.log();
    };

    function Speed(settings) {
      _.append(this, settings);
      this.callbacks = {};
      this.anonymusCount = 0;
    }

    Speed.prototype.add = function(name, func) {
      var ref;
      ref = resolveNameFunc(this, name, func), name = ref[0], func = ref[1];
      if ((!this.callbacks[name]) && _.isFunction(func)) {
        this.callbacks[name] = func;
      }
      return this;
    };

    Speed.prototype.run = function(name, func) {
      var callback, ref, ref1;
      ref = resolveNameFunc(this, name, func), name = ref[0], func = ref[1];
      if (name != null) {
        Speed.run(func, this.calls, this.rounds, this.details, name);
      } else {
        ref1 = this.callbacks;
        for (name in ref1) {
          callback = ref1[name];
          Speed.run(callback, this.calls, this.rounds, this.details, name);
        }
      }
      return this;
    };

    return Speed;

  })();

  if (typeof module !== "undefined" && module !== null) {
    module.exports = Speed;
  } else if (typeof window !== "undefined" && window !== null) {
    window.Speed = Speed;
  }

}).call(this);
